config/routes.rb
Rails.application.routes.draw do
  get 'orders/new'

  get 'orders/show'

	root "pastries#index"
	resources :pastries do
		resources :orders, only: [:new, :create, :show]
	end
	resource :session, only: [:new, :edit, :create]
	resources :users, except: [:show, :index] do
		resources :pastries, only: [:index]
	end
end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :user
	belongs_to :pastry
end

app/models/pastry.rb
class Pastry < ActiveRecord::Base
	belongs_to :user
	has_many :orders
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :pastries
	has_many :orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	
	helper_method :logged_in?, :current_user
	
	def logged_in?
		session[:user_id].present?
	end
	
	def current_user
		User.find(session[:user_id])
	end
	
	def require_user
		unless logged_in?
			flash[:error]="You must be logged in to do that."
			redirect_to new_session_path
		end
	end
	
	def current_user
		User.find(session[:user_id])
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def new
		@pastry = Pastry.find(params[:pastry_id])
		@order = @pastry.orders.new
  end
	
	def create
		
	end

  def show
  end
end

app/controllers/pastries_controller.rb
class PastriesController < ApplicationController
	before_action :require_user, except: [:index,:show]
########################################################################################################
	def index
		if params[:user_id].present?
			@user = User.find(params[:user_id])
			@pastries = @user.pastries
		else
			@pastries = Pastry.all
		end
		@pastries = Pastry.all
  end
########################################################################################################
  def show
		@pastry=Pastry.find(params[:id])
  end	
########################################################################################################
  def new
		@pastry = Pastry.new
  end
	
	def create
		@pastry = current_user.pastries.new(pastry_params)
		if @pastry.save
			flash[:success]="Pastry added!"
			redirect_to root_path
		else
			flash[:error]="Oops, try again."
			render :new
		end
	end
########################################################################################################
  def edit
		@pastry = Pastry.find(params[:id])
  end
	
	def update
		@pastry = Pastry.find(params[:id])
		if @pastry.update(pastry_params)
			flash[:success]="Pastry updated!"
			redirect_to root_path
		else
			flash[:error]="Oops, try again."
			render :edit
		end
	end
########################################################################################################
	def destroy
		pastry = Pastry.find(params[:id])
		pastry.destroy
		flash[:success]="Entry Deleted"
		redirect_to root_path
	end
########################################################################################################
#------------------------------------------------------------------------------------------------------#
########################################################################################################
	private
	def pastry_params
		params.require(:pastry).permit(:name, :price_in_pence, :description)
	end
########################################################################################################
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
	
	def create
		username = params[:session][:username]
		password = params[:session][:password]
		@user = User.find_by(username: username)
		if @user.present? and @user.authenticate(password)
			flash[:success]="Logged in"
			session[:user_id]=@user.id
			redirect_to root_path
		else
			flash[:error]="Oops, try again"
			render :new
		end
	end

  def show
  end
	
	def destroy
		reset_session
		flash[:success]="Logged Out"
		redirect_to root_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
##########################################################################################################
  def new
		@user = User.new
  end
	
	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success]="User added!"
			reset_session
			session[:user_id]=@user.id
			redirect_to root_path
		else
			flash[:error]="Oops, try again."
			render :new
		end
	end
##########################################################################################################
  def edit
		@user = User.find(params[:id])
  end
	
	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			flash[:success]="User updated!"
			redirect_to root_path
		else
			flash[:error]="Oops, try again."
			render :edit
		end
	end
##########################################################################################################
	def destroy
		user = User.find(params[:id])
		user.destroy
		flash[:success]="User Deleted"
		redirect_to root_path
	end
##########################################################################################################
#--------------------------------------------------------------------------------------------------------#
##########################################################################################################
	private
	def user_params
		params.require(:user).permit(:username, :email, :password, :password_confirmation)
	end
##########################################################################################################
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pastries_helper.rb
module PastriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Breakfastr</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%s= csrf_meta_tags %>
		<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
		<script type="text/javascript">
		// This identifies your website in the createToken call below
		Stripe.setPublishableKey('pk_test_sy796A9qIO57kksPoGsY5Z71');
		// ...
			jQuery(function($) {
				$('#payment-form').submit(function(event) {
					var $form = $(this);

					// Disable the submit button to prevent repeated clicks
					$form.find('button').prop('disabled', true);

					Stripe.card.createToken($form, stripeResponseHandler);

					// Prevent the form from submitting with the default action
					return false;
				});
			});
			function stripeResponseHandler(status, response) {
				var $form = $('#payment-form');

				if (response.error) {
					// Show the errors on the form
					$form.find('.payment-errors').text(response.error.message);
					$form.find('button').prop('disabled', false);
				} else {
					// response contains id and card, which contains additional card details
					var token = response.id;
					// Insert the token into the form so it gets submitted to the server
					$form.append($('<input type="hidden" name="order[stripe_token]" />').val(token));
					// and submit
					$form.get(0).submit();
				}
			};
		</script>
	</head>
	<body>
		<header>
			<%= link_to "Breakfastr", root_path %>
			<% if logged_in? %>	
				<%= link_to "Add a pastry", new_pastry_path %>
				<%= link_to "Log out", session_path, method: :delete %>
			<% else %>
				<%= link_to "Log in", new_session_path %>
				<%= link_to "Sign Up", new_user_path %>
			<% end %>
		</header>

		<% flash.each do | k,v | %>
			<div class="flash <%= k %>">
				<p><%= v %></p>
			</div>
		<% end %>

		<%= yield %>

	</body>
</html>

app/views/orders/new.html.erb
<h1>Pay for your <%= @pastry.name %> below.</h1>
<%= simple_form_for [@pastry, @order], url: pastry_orders_path do | f | %>
<span class="payment-errors"></span>
  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
      <input type="text" size="2" data-stripe="exp-month"/>
    </label>
    <span> / </span>
    <input type="text" size="4" data-stripe="exp-year"/>
  </div>

  <button type="submit">Submit Payment</button>

<% end %>

app/views/orders/show.html.erb
<h1>Orders#show</h1>
<p>Find me in app/views/orders/show.html.erb</p>

app/views/pastries/edit.html.erb
<h1>Edit <%= @pastry.name %></h1>
<%= simple_form_for @pastry do | f |  %>
	<%= f.input :name %>
	<%= f.input :price_in_pence %>
	<%= f.input :description %>
	<%= f.button :submit %>
<% end %>

app/views/pastries/index.html.erb
<h1>Latest Pastries fresh out of the oven!</h1>
<!-- ################################################################################################## -->
<section class="pastries">
	<% @pastries.each do | pastry | %>
		<div class="pastry">
			<p><%= link_to pastry[:name],pastry_path(pastry) %> </p>
			<p><%= pastry[:price_in_pence] %> </p>
		</div>
	<% end %>
</section>

app/views/pastries/new.html.erb
<h1>Add a new Pastry to Breakfastr</h1>
<%= simple_form_for @pastry do | f |  %>
	<%= f.input :name %>
	<%= f.input :price_in_pence %>
	<%= f.input :description %>
	<%= f.button :submit %>
<% end %>

app/views/pastries/show.html.erb
<section class="pastry">
  <h1><%= @pastry.name %></h1>
	<p>
		<%= link_to new_pastry_order_path(@pastry) do %>
			<%= number_to_currency(@pastry.price_in_pence.to_f/100, unit:"£")%>
		<% end %>
	</p>
	<p><%= @pastry.description %></p>
	<p>Baked by <%= @pastry.user.username %></p>
	
	<% if logged_in? %> <!-- and current_user.owns(@pastry) -->
		<div class="actions">
			<%= link_to "Edit", edit_pastry_path(@pastry) %>
			<%= link_to "Remove this pastry from the bakery", pastry_path(@pastry), method: :delete %>
		</div>
	<% end %>
	
</section>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up For Pastries!</h1>
<%= simple_form_for @user do | f | %>
	<%= f.input :username %>
	<%= f.input :email %>
	<%= f.input :password %>
	<%= f.input :password_confirmation %>

	<%= f.button :submit %>
<% end %>